#training options
NAME: SEnSeI-DLv3_S2L8
STEPS_PER_EPOCH: 500 #1000
EPOCHS: 55 #200
BATCH_SIZE: 4 #8
PATCH_SIZE: 384 #257
CLASSES: 2

#Base model options
SENSEI: True
CONVERSION_BLOCK: False
MODEL_TYPE: 'mfcnn'

SENSEI_PATH: './SenSei/sensei_pretrained_198.h5'
MODEL_SAVE_PATH: "./model_jetbrains"
SENTINEL_PATHS: "./mfcnn_common_model/sentset_for_common_model.pkl"
LANDSAT_PATHS: "./mfcnn_common_model/landset_for_common_model.pkl"
DESCRIPTOR_PATH_LANDSAT: "./SenSei/landsat_metadata.yaml"
DESCRIPTOR_PATH_SENTINEL: "./SenSei/sentinel_metadata.yaml"

DESCRIPTOR_STYLE: 'log' # best to keep this as it is, SEnSeI is currently only trained with this style, although loader.Dataloader also supports 'bandpass', which has 6 features per spectrum